### ISSUE TITLE
Number of SPP per training iteration and inc/exp flag

### ISSUE THREAD

**Issue by sherholz** [cgtuebingen/robust-vmm-guiding#1]
At the moment the (max) num of SPP per training iteration is not configurable via the GUI and set to 4spp.
In addition, the behavior of the SPP per iteration is unintuitive (4, 8, 16). The latter is due to being able to 
still compare exponential and incremental training.

To make it possible to also use incremental learning with 1SPP and being able to show that our algorithm is still robust (even when setting the num of VMM initial components to 1 :)), this option should be made available again.
Also, the behavior should be changed to always using the number of set samples (getting rid of the exponential behavior).
To be able to still compare inc vs exp training a boolean flag can be added (we do not need to expose this to the GUI since this experiment is only for internal use) to switch the behavior of the max num spp per iteration parameter.

I also think it would make be useful to mention the ability to do incremental training with 1SPP and even 1 component in the readme (with a small example comparing it to the settings in the paper).
This "really" proves the robustness of our method and is a big selling point.

**Comment by LukasRuppert** [comment]
Check out commit 765cb73af90329db9b27fa595f6634ff907f77a4 and see if that works for you.
I still need to update the readme.
